# Generated by Django 6.0.4 on 2026-05-01 14:29

import django.db.models.deletion
import processor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=processor.models.upload_original_path, verbose_name='Arquivo TXT')),
                ('detected_layout_type', models.CharField(blank=True, help_text='Copia do layout_type da Empresa no momento do upload.', max_length=32, verbose_name='Layout aplicado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('DONE', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=16, verbose_name='Status')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Linhas/Registros gerados')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('web_csv', models.FileField(blank=True, null=True, upload_to=processor.models.upload_output_path, verbose_name='CSV Web (1:1)')),
                ('print_csv', models.FileField(blank=True, null=True, upload_to=processor.models.upload_output_path, verbose_name='CSV Impressão (Dobra A/B)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='people.empresa')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'created_at'], name='processor_u_empresa_aa5036_idx'), models.Index(fields=['status', 'created_at'], name='processor_u_status_7b4a74_idx')],
            },
        ),
    ]
