# Generated by Django 6.0.4 on 2026-05-01 21:00

import processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_sourcesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesystem',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gerado em'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='layout_spec',
            field=models.JSONField(blank=True, null=True, verbose_name='Especificação do layout'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='sample_file',
            field=models.FileField(blank=True, null=True, upload_to=processor.models.system_sample_path, verbose_name='Arquivo modelo'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='sample_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA-256 do modelo'),
        ),
    ]
