# Generated by Django 6.0.4 on 2026-05-01 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Razão social / Nome')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('cnpj', models.CharField(help_text='Armazenado somente com dígitos (ex.: 11437239000140).', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', message='Informe 14 dígitos para o CNPJ.')], verbose_name='CNPJ (14 dígitos)')),
                ('layout_type', models.CharField(choices=[('FOLHAMATIC', 'Folhamatic'), ('RMLABORE_DEFAULT', 'RM Labore (Default)'), ('RMLABORE_CUSTOM', 'RM Labore (Custom)'), ('GENESIS', 'Genesis'), ('CONTIMATIC', 'Contimatic')], default='RMLABORE_DEFAULT', max_length=32, verbose_name='Layout do TXT')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'constraints': [models.CheckConstraint(condition=models.Q(('cnpj', ''), _negated=True), name='people_empresa_cnpj_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('role', models.CharField(blank=True, max_length=80, verbose_name='Cargo/Função')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='people.empresa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'indexes': [models.Index(fields=['empresa', 'name'], name='people_cont_empresa_93946b_idx')],
            },
        ),
    ]
