# Generated by Django 6.0.4 on 2026-05-01 19:57

import people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=people.models.empresa_logo_path, verbose_name='Logo'),
        ),
    ]
