# Generated by Django 6.0.4 on 2026-05-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_empresa_logo'),
        ('processor', '0002_sourcesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='source_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='processor.sourcesystem', verbose_name='Sistema de origem'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='layout_type',
            field=models.CharField(default='RMLABORE_DEFAULT', max_length=32, verbose_name='Layout do TXT'),
        ),
    ]
